### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 360add** [KroMiose/nonebot_plugin_dice_narrator#1]
![~NE_((MGBEA`2SXWBENKWSP](https://github.com/KroMiose/nonebot_plugin_dice_narrator/assets/140232510/408568de-eae9-4efb-97d6-bfdadc1cbacc)
![`081WC@WP%UDGA`BI5DAAQ2](https://github.com/KroMiose/nonebot_plugin_dice_narrator/assets/140232510/de10f77b-1cab-4668-9856-0be83a5078ae)

**Comment by 360add** [comment]
![~NE_((MGBEA`2SXWBENKWSP](https://github.com/KroMiose/nonebot_plugin_dice_narrator/assets/140232510/6b803e99-a6ab-4aa5-8875-f97443ba646c)

**Comment by KroMiose** [comment]
这个报错是因为gpt返回的信息不是标准yaml格式，请提供更详细的case

**Comment by 360add** [comment]
![image](https://github.com/KroMiose/nonebot_plugin_dice_narrator/assets/140232510/e5abdc50-6ef3-400a-b986-bd59c617b6f2)

**Comment by 360add** [comment]
![image](https://github.com/KroMiose/nonebot_plugin_dice_narrator/assets/140232510/eaccb016-8d23-4ad3-a476-1868e3b311dd)

**Comment by Tigrex-Dai** [comment]
我也是相同的两个报错，即使填好了所需信息也无法正常启动

**Comment by KroMiose** [comment]
更新了一下项目依赖，尝试更新或重装试试？

**Comment by 360add** [comment]
更新了没有用，还是一模一样的报错

**Comment by Tigrex-Dai** [comment]
您好，我每次报错以后配置文件内填好的key等内容都会清空（回到初始状态），不知道是否与issue有关

**Comment by KroMiose** [comment]
可能是配置填写的格式有误（不符合yaml格式要求），导致无法解析

**Comment by Tigrex-Dai** [comment]
您好，我试过
1. [sk-xxxxxxxxx]
2. ['sk-xxxxxxxx']
3. 'sk-xxxxxxxxx'
4. 另起一行缩进后 - sk - xxxxxxxxx
都是同样的报错

**Comment by KroMiose** [comment]
![image](https://github.com/KroMiose/nonebot_plugin_dice_narrator/assets/57167362/4a887e7b-de6d-4d03-904a-4f592eb51dab)
参考这个方式填写， `sk-xxxx` 中间 `-` 前后不要带空格，key前后不用带引号，另外你的问题是“报错”还是“配置重置”？报错可能是依赖问题或者插件冲突；重置则是配置格式问题

**Comment by Tigrex-Dai** [comment]
您好，我的问题是既报错又重置
![image](https://github.com/KroMiose/nonebot_plugin_dice_narrator/assets/26639371/35827987-9eb6-4e37-b3b0-aad4576b3360)
我搜索了一下报错信息，是在某个地方出现了一个奇怪的字符：0xca
而报错以后配置文件自动重置了，我检查了一下配置文件，发现也并没有什么隐藏的字符

**Comment by Tigrex-Dai** [comment]
我解决这个问题了，我在notepad++里把编码设置为utf-8后保存并覆盖了原配置文件， @360add  可以结合上面的配置格式试试看！

**Comment by 360add** [comment]
文件发一个呀xd，key别发

**Comment by 360add** [comment]
> 我解决这个问题了，我在notepad++里把编码设置为utf-8后保存并覆盖了原配置文件， @360add 可以结合上面的配置格式试试看！

文件发一个呀xd，key别发

**Comment by 360add** [comment]
> 我解决这个问题了，我在notepad++里把编码设置为utf-8后保存并覆盖了原配置文件， @360add 可以结合上面的配置格式试试看！

成了，xd，还得是你
